export const ALL_login_REQUESTS = "ALL_login_REQUESTS";

export const ALL_login_SUCCESS = "ALL_login_SUCCESS";

export const ALL_login_FAILURE = "ALL_login_FAILURE";


export const ALL_Register_REQUESTS = "ALL_Register_REQUESTS";

export const ALL_Register_SUCCESS = "ALL_Register_SUCCESS";

export const ALL_Register_FAILURE = "ALL_Register_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const PROFILE_REQUEST = " PROFILE_REQUEST";
export const PROFILE_SUCCESS = " PROFILE_SUCCESS"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"

export const UPDATE_password_REQUEST = "UPDATE_password_REQUEST"

export const UPDATE_password_SUCCESS = "UPDATE_password_SUCCESS"

export const UPDATE_password_FAIL = "UPDATE_password_FAIL"

export const PROFILE_FAIL = " PROFILE_FAIL"
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'; 
export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT'

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const  CLEAR_ERRORS = " CLEAR_ERRORS"